from typing import Protocol, Optional, List
from app.domain.invoice import ProcessedInvoice, Decision, AgentStep
from app.domain.policy import Policy, CompiledRule


class LLMClient(Protocol):
    def chat(self, messages: list, model: str = "llama-3.3-70b-versatile") -> str: ...
    def embed(self, text: str) -> list[float]: ...


class FraudGraphClient(Protocol):
    def get_vendor_risk(self, vendor_name: str) -> dict: ...
    def check_bank_account_sharing(self, vendor_name: str) -> bool: ...
    def get_betweenness_centrality(self, vendor_name: str) -> float: ...


class AuditRepository(Protocol):
    def append(self, invoice_id: str, event_type: str, actor: str, payload: dict) -> str: ...  # returns chain_hash
    def get_chain(self, invoice_id: str) -> list[dict]: ...


class InvoiceRepository(Protocol):
    def get(self, invoice_id: str) -> Optional[ProcessedInvoice]: ...
    def update_decision(self, invoice_id: str, decision: Decision) -> None: ...


class FeedbackRepository(Protocol):
    def get_similar_corrections(self, embedding: list[float], limit: int = 3) -> list[dict]: ...
    def save_correction(self, invoice_id: str, agent_decision: str, human_decision: str, reason: str) -> None: ...


class PolicyRepository(Protocol):
    def get_active(self) -> list[Policy]: ...
    def save(self, policy: Policy) -> str: ...
    def update_active(self, policy_id: str, active: bool) -> None: ...


class EventPublisher(Protocol):
    def publish_decision(self, decision: Decision) -> None: ...
